version: 2
updates:
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mohith7007"
    assignees:
      - "mohith7007"

  # Enable version updates for Node.js packages
  - package-ecosystem: "npm"
    directory: "/finbot-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mohith7007"
    assignees:
      - "mohith7007"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mohith7007"
    assignees:
      - "mohith7007"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mohith7007"
    assignees:
      - "mohith7007"
