apiVersion: 1

datasources:
  - name: Finbot Timescale
    uid: finbot-timescale
    type: postgres
    access: proxy
    url: timescale:5432
    user: finbot
    database: finbot
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1200
    secureJsonData:
      password: finbot
